# dotfiles bash config

[ -r "$HOME/.local/share/dotfiles/shell-config.sh" ] && . "$HOME/.local/share/dotfiles/shell-config.sh"

# Git branch/tab completion and git aliases.
[ -r "$HOME/.local/share/dotfiles/git-completion.sh" ] && . "$HOME/.local/share/dotfiles/git-completion.sh"
