set ts=2 sts=2 sw=2 et
set ai
set tw=80

set nocompatible
set nofoldenable
set shm+=I
set ruler
set noerrorbells

set list listchars=tab:»·,trail:·

filetype plugin on
syntax enable

au BufNewFile,BufRead Makefile set noet

autocmd BufNewFile,BufRead *.scad set ft=c
